ALTER TABLE BRUKER ADD COLUMN er_sykmeldt NUMBER(1, 0) NOT NULL;
ALTER TABLE BRUKER ADD COLUMN har_arbeidsgiver NUMBER(1, 0) NOT NULL;
ALTER TABLE BRUKER ADD COLUMN servicegruppekode NVARCHAR2(255) NOT NULL;